version: "3"

services:
  react-app:
    build: ./Dockerfile.client
    ports:
      - "5173:5173"
    volumes:
      - ./react-app:/app

  server:
    build: ./Dockerfile.server
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

