version: "3"

services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    volumes:
      - ./react-app:/app

  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true


