version: "3"

services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    # volumes:
    #   - ./client/:/app
    networks:
      - my-network

  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    networks:
      - my-network
    stdin_open: true
    tty: true

networks:
  my-network:
