name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build Docker Image
        run: docker build -t yishaigalili/project_js:1.0 .

      - name: Log in to Docker Hub
        run: docker login -u yishaigalili -p dckr_pat_2XqVygGaAeZ7ZlByCHcv2zEyC-I

      - name: Push Docker Image
        run: docker push yishaigalili/project_js:1.0